export const ACTIVE_USER_WINDOW_MINUTES = parseInt(process.env.ACTIVE_USER_WINDOW_MINUTES || '5', 10);
export const STUDENT_INACTIVITY_TIMEOUT_MINUTES = parseInt(process.env.STUDENT_INACTIVITY_TIMEOUT_MINUTES || '60', 10);
